### ISSUE TITLE
Need a release version which is upper than 0.1.0

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-devops-helm-chart#2]
![image](https://user-images.githubusercontent.com/1450685/133031054-c5c1d9c1-d359-4627-b4c3-41f591955dcc.png)

As you can see from the above screenshot. We cannot publish the next release base on [0.0.4](https://github.com/kubesphere-sigs/ks-devops-helm-chart/releases/tag/ks-devops-0.0.4). Suggested version:

* `0.1.1`

## References
* https://github.com/kubesphere/ks-installer/tree/master/roles/ks-devops/files/ks-devops/charts

**Comment by JohnNiang** [comment]
Agree with you.
