### ISSUE TITLE
Request to add more pod template for newer DevOps agents

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere-sigs/ks-devops-helm-chart#28]
Currently, we've add some fresh DevOps agents in https://github.com/kubesphere/devops-agent, please see:

- Add new DevOps agent for Golang 1.16.8 ([#39](https://github.com/kubesphere/devops-agent/pull/39))
- Add new DevOps agent for Maven with JDK 11 ([#38](https://github.com/kubesphere/devops-agent/pull/38/files))
- Add new DevOps agent for Python 3.7 ([#31](https://github.com/kubesphere/devops-agent/pull/31))
- Add new DevOps agent for Dotnet 5 ([#24](https://github.com/kubesphere/devops-agent/pull/24))

It's time to add them into `jenkins-casc-config` ConfigMap.

/kind feature

**Comment by JohnNiang** [comment]
Because there are still some agents left to complete, I will reopen this issue.
/reopen

**Comment by mangoGoForward** [comment]
I can not find docker images about `builder-dotnet`, and image  of `builder-python` has no tag with python 3.7. Could we provide those later?

**Comment by JohnNiang** [comment]
@mangoGoForward 

For `builder-dotnet`, please see the latest action in devops agent repository: https://github.com/kubesphere/devops-agent/actions/runs/1398472523, the build for DotNet failed. We are trying out it.

For `builder-python`, please see:

![image](https://user-images.githubusercontent.com/16865714/140002460-44480b95-64ff-49fc-9ae5-9d7445191a9b.png)

**Comment by Dishone** [comment]
> @mangoGoForward
> 
> For `builder-dotnet`, please see the latest action in devops agent repository: https://github.com/kubesphere/devops-agent/actions/runs/1398472523, the build for DotNet failed. We are trying out it.
> 
> For `builder-python`, please see:
> 
> ![image](https://user-images.githubusercontent.com/16865714/140002460-44480b95-64ff-49fc-9ae5-9d7445191a9b.png)
https://github.com/kubesphere/devops-agent/pull/54
