### ISSUE TITLE
[Jenkins] Request to set the number of executors on the build-in node to 0

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-devops-helm-chart#49]
Building on the built-in node can be a security issue. You should set the number of executors on the built-in node to 0. See [the documentation](https://www.jenkins.io/doc/book/security/controller-isolation/).

/good-first-issue

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this?

**Comment by LinuxSuRen** [comment]
Of course! @mohitsaxenaknoldus 
/assign @mohitsaxenaknoldus

**Comment by mohitsaxenaknoldus** [comment]
So, do you have your Jenkins hosted somewhere? I don't see a Jenkinsfile in this repo either.

**Comment by LinuxSuRen** [comment]
I guess you probably need to install it by yourself.

**Comment by mohitsaxenaknoldus** [comment]
I do have Jenkins and Helm installed. How can I build/view this project on Jenkins?

**Comment by LinuxSuRen** [comment]
You can use the following helm repo:

`helm repo add ks-devops https://kubesphere-sigs.github.io/ks-devops-helm-chart/`

**Comment by JohnNiang** [comment]
I think this issue might be resolved by #52, please help to see if it is correct. @kubesphere-sigs/sig-devops

**Comment by LinuxSuRen** [comment]
hi @JohnNiang , thanks for your reminder.
/close
